[WIP]add: shared preference.
torkralle/notion_wordbook pull request #30
Opened 2022-04-10 12:29 UTC by torkralle

## 目的
localにデータを保存する

## 更新内容
SharedPreferenceを使って、データを永続化する

## 関連するIssue等
#27 

## レビューポイント

## 留意事項

## 残課題
* riverpod内で利用できない

2022-04-25 04:14 UTC, noriHanda commented
@torkralle レビューもうちょい待った方が良いでしょうか！

2022-04-26 01:37 UTC, torkralle commented
> @torkralle レビューもうちょい待った方が良いでしょうか！

@noriHanda 
デバッグコード消したんで、レビューお願いします！

2022-04-26 03:43 UTC, noriHanda commented
@torkralle ういっす！

2022-04-26 04:44 UTC, noriHanda requested changes
結構大きな機能追加だったのでお疲れ様です！ちょっとずつ改善できそうなところを見つけたのでお願いします！

2022-04-26 04:44 UTC, noriHanda commented on lib/screens/add_wordbook_page.dart
> +            appBar: AppBar(
ここ、 connecting_page.dart でも使ってるので抽出して使い回しできるようにしたいですね。

2022-04-26 04:44 UTC, noriHanda commented on lib/screens/add_wordbook_page.dart
> +class WordbookNameField extends HookConsumerWidget {
これは使い回しする予定があります？もしある場合は、別ファイルにしておいた方が他のページで使う際に探すのが楽かなと思います。違う場合は引数に labelName を取らずに決め打ちしちゃった方が良いと思うのですが、どうでしょう？

2022-04-26 04:44 UTC, noriHanda commented on lib/screens/connecting_page.dart
> +        Navigator.of(context).pushNamed('/home');
ここ、タップ後は戻れるようにしたくないので `pushNamedAndRemoveUntil` 使うのが良さそうですね。よろしくお願いします。

2022-04-26 04:44 UTC, noriHanda commented on lib/screens/connecting_page.dart
> +      child: Container(
この部分は add_wordbook_page.dart の次へボタンと同じなので Widget にしちゃいましょう。

2022-04-26 04:44 UTC, noriHanda commented on lib/screens/connecting_page.dart
> +        Navigator.of(context).pushNamed('/home');
あ、ここタップ後 bottom_navbar が表示されませんね。修正よろしくお願いします。

2022-04-26 04:44 UTC, noriHanda commented on lib/screens/home_page.dart
> +                '前回正答率' + wordbooks[index]['api_key'], // TODO: api_keyを暫定的に表示
この TODO は別 issue とかで解消って感じですか？

2022-04-26 04:44 UTC, noriHanda commented on lib/screens/connecting_page.dart
> +            onChanged: (text) {
ここで状態変更するよりも、連携ボタン押したら変更するってした方（setDbInfo でstateも変えるとか、setDbInfo使わなくて直接 sharedpreferences叩くとか）が良いと思うのですが、どうでしょう？コードの構成的によりシンプルになるのかなと思います。

2022-04-26 04:44 UTC, noriHanda commented on lib/viewmodels/wordbook_info.dart
> +  Future<void> setDBInfo() async {
ここがstateを使わなくても書けそうなので StateNotifier の外で書いても良いのかなと思いました。

2022-04-27 12:43 UTC, torkralle commented on lib/screens/home_page.dart
> +                '前回正答率' + wordbooks[index]['api_key'], // TODO: api_keyを暫定的に表示
@noriHanda 
回答率はテストページと絡むからそっちでやりたい！

2022-04-27 12:46 UTC, torkralle commented on lib/screens/connecting_page.dart
> +            onChanged: (text) {
@noriHanda 
そうなんだよね。。
textfieldの情報をどこで取るかがわからないから、ひとまずこうしてみたんよ。

連携ボタンを押すときにTextFiledの値どこから取れるか知ってたりする？

2022-04-27 12:51 UTC, torkralle commented on lib/viewmodels/wordbook_info.dart
> +  Future<void> setDBInfo() async {
@noriHanda 
setDBInfoのことかな？
ごめん、これってstate使わなくても書けるかな？
ちょっと思い浮かばなくて、教えてほしい。。。

apiKey, dbIDについてはstate使わなくても行けそうだけど、
db_nameは一旦stateに保存したものを利用するしか思いつかない。。

2022-04-28 05:54 UTC, noriHanda commented on lib/screens/home_page.dart
> +                '前回正答率' + wordbooks[index]['api_key'], // TODO: api_keyを暫定的に表示
OKです！Issue にしといてもらえると助かります！

2022-04-28 05:55 UTC, noriHanda commented on lib/screens/connecting_page.dart
> +            onChanged: (text) {
textEditingController的なのを定義したらできたきが。
https://docs.flutter.dev/cookbook/forms/retrieve-input

こんな感じですかね！

2022-04-28 07:47 UTC, noriHanda commented on lib/viewmodels/wordbook_info.dart
> +  Future<void> setDBInfo() async {
あ、確かに dbName は state 管理するやつっすね🙇‍♂️ そのままで大丈夫です！
ただtextEditingController 使ってると api_key と db_id は状態に保存しなくても良いからそうした方が良いかもと思いました。（結合度を下げられそう的な）

2022-04-29 06:21 UTC, torkralle commented on lib/screens/connecting_page.dart
> +            onChanged: (text) {
ありがと！修正してみたので確認お願いします！

2022-04-29 06:22 UTC, torkralle commented on lib/screens/add_wordbook_page.dart
> +class WordbookNameField extends HookConsumerWidget {
共通化したので確認お願い！

2022-04-29 06:27 UTC, torkralle commented on lib/screens/connecting_page.dart
> +        Navigator.of(context).pushNamed('/home');
あ、たしかにそういうふうに書かれてたね。
私の方で修正しておいたので、確認お願い！

2022-04-29 06:37 UTC, torkralle commented on lib/screens/connecting_page.dart
> +      child: Container(
修正したので、確認よろしく！

2022-04-29 06:48 UTC, torkralle commented on lib/screens/add_wordbook_page.dart
> +            appBar: AppBar(
修正したので、確認お願いしたい！

2022-05-15 11:40 UTC, noriHanda commented on lib/screens/connecting_page.dart
> +        Navigator.of(context).pushNamed('/home');
戻った時に画面のリビルドがかからないから「あれ、追加されない」ってなっちゃいそうですね ^^;
単語帳一覧の画面のListViewの設定でフォーカスを得るとビルドし直す的な感じにしたいですが、これは別 issue にしますか。

2022-05-15 11:44 UTC, noriHanda approved these changes
レビュー遅れてすみません！ちょこっと修正だけだったんでやっちゃいました！お疲れ様です 🙏

2022-05-18 11:17 UTC, merged