[WIP]Quizページ
torkralle/notion_wordbook pull request #36
Opened 2022-05-08 05:39 UTC by USK314

## 目的
クイズページの作成

## 更新内容
- UI部分を作った
- currentPageを表示できるようにした

## 関連するIssue等
resolved #23
resolved #31 

## レビューポイント

## 留意事項

## 残課題
maxPageの表示

2022-05-08 05:43 UTC, USK314 commented
https://prod.liveshare.vsengsaas.visualstudio.com/join?0F8D749721F32772447B7895F1C64339A751

2022-05-21 11:38 UTC, noriHanda commented on .vscode/launch.json
> +{
このファイル何か知ってる？いらなければ消してもらえると。

2022-05-21 11:40 UTC, noriHanda commented on lib/objects/models/word.dart
> +
あ、ここ結局使わなかったから消して良いね。1, 2 行目の Project imports: が謎に2つあるのも一緒に消しといてください。

2022-05-21 11:49 UTC, noriHanda commented on lib/screens/quiz_page/components/answer_candidate_card.dart
> +    // required this.isCorrect,
これコメントアウトで残してるの良いね👍

2022-05-21 11:51 UTC, noriHanda commented on lib/screens/quiz_page/components/progress_bar.dart
> +      color: Color.fromARGB(255, 112, 33, 181),
テーマカラーどっか別ファイルに決めてそこの変数使うってしたいね。（別issueにしたらそれで良いと思います。）

2022-05-21 12:05 UTC, noriHanda requested changes
少々修正点あったのでよろです！！

2022-05-21 12:05 UTC, noriHanda commented on lib/screens/quiz_page/quiz_page.dart
> +              Flexible(
ここも抽出した方が isCorrect 使いたい時に修正しやすいのかなと思います。

2022-05-22 10:52 UTC, torkralle requested changes

2022-05-22 10:52 UTC, torkralle commented on lib/main.dart
> +        '/quiz_page': (context) => QuizPage(),
なんとなく揃ってないの気持ち悪いので、
/quiz_page→/quizでお願いします！

2022-05-22 10:52 UTC, torkralle commented on lib/viewmodels/page_controllers.dart
> +  void increasePage() => state++;
細かいけど、
Pageを増やすよりPageCountとかPageNumにしといたほうがわかりやすいかなと思いました！

2022-05-30 11:49 UTC, USK314 commented on lib/objects/models/word.dart
> +
これから使う可能性とかもないんですか？

2022-05-30 13:34 UTC, USK314 commented on lib/screens/quiz_page/quiz_page.dart
> +                    return AlertDialog(
いや、分けます

2022-05-30 13:45 UTC, USK314 commented on lib/screens/quiz_page/quiz_page.dart
> +              Flexible(
命名を`AnswerCandidateCardList`にしたんですけどもっといいやつあったらお願いします！

2022-05-30 14:26 UTC, noriHanda commented on lib/screens/quiz_page/components/progress_bar.dart
> +      color: Color.fromARGB(255, 112, 33, 181),
うん

2022-05-30 14:29 UTC, noriHanda commented on lib/screens/quiz_page/quiz_page.dart
> +              Flexible(
`ChoiceList`

2022-06-02 03:20 UTC, noriHanda approved these changes
LGTM

2022-06-03 03:10 UTC, merged