単語帳内の単語が見れるように
torkralle/notion_wordbook pull request #46
Opened 2022-06-13 00:44 UTC by torkralle

## 目的
単語帳内の単語が見れるように

## 更新内容
- Providerに単語一覧を追加
- 単語一覧を画面で表示

## 関連するIssue等
#45 

## レビューポイント

## 留意事項

## 残課題

2022-06-19 15:38 UTC, noriHanda commented on lib/screens/home_page.dart
> +import '../viewmodels/word_list_controller.dart';
絶対パスでお願いします。

2022-06-19 15:42 UTC, noriHanda approved these changes
LGTM

2022-06-19 15:46 UTC, noriHanda commented
@torkralle ブランチの名前とコミットの内容全然違って草

2022-06-22 14:55 UTC, noriHanda requested changes
不要なメソッドが多くなってきていたのでそれの修正お願いします！

2022-06-22 14:55 UTC, noriHanda commented on lib/viewmodels/wordbook_info.dart
> +  WordbookInfo getWordBookInfo() {
このメソッド要らなそうですね。

2022-06-22 14:55 UTC, noriHanda commented on lib/viewmodels/wordbook_info.dart
> +  String getAPIKey() {
このメソッドも要らなそうですね

2022-06-22 14:55 UTC, noriHanda commented on lib/viewmodels/wordbook_info.dart
> +  String getDBId() {
このメソッドも要らなそうですね。

2022-06-22 14:55 UTC, noriHanda commented on lib/viewmodels/wordbook_info.dart
>      return state.dbName;
このメソッドも要らなそうですね。

2022-06-26 12:27 UTC, torkralle commented on lib/viewmodels/wordbook_info.dart
> +  WordbookInfo getWordBookInfo() {
ここらへんは直でリードできそう。
→いらない

2022-06-27 03:16 UTC, merged