正解の単語と、ランダムな単語を3つ取得
torkralle/notion_wordbook pull request #47
Opened 2022-06-13 05:15 UTC by torkralle

## 目的
選択肢の作成

## 更新内容
ランダムに3つ単語を持ってくる

## 関連するIssue等
#39

## レビューポイント

## 留意事項

## 残課題

2022-06-19 15:09 UTC, noriHanda commented on lib/screens/quiz_page/components/progress_bar.dart
> +import '../../../viewmodels/word_list_controller.dart';
今のところは絶対パスに統一でよろしくお願いします。

2022-06-19 15:12 UTC, noriHanda commented on lib/viewmodels/word_list_controller.dart
> +      var choices = [
`var` より `List<String>` とかの方が色々と良いと思います！

2022-06-19 15:12 UTC, noriHanda commented on lib/viewmodels/word_list_controller.dart
> +    var list = [];
ここもですね。

2022-06-19 15:14 UTC, noriHanda commented on lib/viewmodels/word_list_controller.dart
> +    for (int i = 0; i < maxPage; i++) {
こういったところに `/// ページの終わりでない場合はリストに追加していく` みたいなドキュメンテーションしていってもらえると助かります！

2022-06-19 15:15 UTC, noriHanda commented on lib/viewmodels/word_list_controller.dart
> +    var choices = [state[currentPage - 1].spelling];
ここも型名明示的に書くのおなしゃす

2022-06-19 15:16 UTC, noriHanda commented on lib/viewmodels/word_choices_controller.dart
> +  getRandomChoices() {
このメソッドは state を返すだけだったらなくても良いですね。

2022-06-19 15:23 UTC, noriHanda commented on lib/screens/home_page.dart
> +        onTap: () async {
`onTap: () async` のところは思考停止で `isLoading` 的な状態を管理して、 `isLoading = true` の時は `CircularProgressIndicator` 出すってした方が良さそうですね。で、エラーとタイムアウトを設けてロードがうまくいかないとアラート出すみたいな。

2022-06-19 15:30 UTC, noriHanda commented on lib/viewmodels/word_list_controller.dart
> +    var choices = [state[currentPage - 1].spelling];
あと、currentPage が max を超えるとここでクラッシュするので修正よろしくお願いします。

2022-06-19 15:30 UTC, noriHanda commented on lib/screens/quiz_page/quiz_page.dart
> +import '../../viewmodels/word_list_controller.dart';
この辺も絶対パスにするのおなしゃす

2022-06-19 15:31 UTC, noriHanda commented on lib/screens/quiz_page/quiz_page.dart
> +    final answerWord = wordsList[currentPage - 1];
この真上に `// ignore: unused_local_variable` つけると warning 消えてくれますよ！

2022-06-19 15:35 UTC, noriHanda requested changes
エラーハンドリングやボタンを押した時に非同期処理になるタイミングでローディングだよって伝えるUI実装よろしくお願いします。（詳しくはコメントに書いています。）

2022-07-03 08:40 UTC, torkralle commented on lib/screens/quiz_page/components/progress_bar.dart
> +import '../../../viewmodels/word_list_controller.dart';
完全に意識の外だった！承知！

2022-07-03 08:42 UTC, torkralle commented on lib/viewmodels/word_list_controller.dart
> +      var choices = [
アザス！了解！

2022-07-03 08:50 UTC, torkralle commented on lib/viewmodels/word_list_controller.dart
> +    for (int i = 0; i < maxPage; i++) {
りょ！

2022-07-03 09:01 UTC, torkralle commented on lib/viewmodels/word_choices_controller.dart
> +  getRandomChoices() {
ok!

2022-07-03 09:03 UTC, torkralle commented on lib/screens/quiz_page/quiz_page.dart
> +import '../../viewmodels/word_list_controller.dart';
shouti!

2022-07-03 09:45 UTC, torkralle commented on lib/screens/home_page.dart
> +        onTap: () async {
やってみた！

2022-07-04 01:31 UTC, noriHanda approved these changes
完璧だと思います！修正ありがとうございました！

2022-07-04 01:32 UTC, merged