add learning_data_page.dart
torkralle/notion_wordbook pull request #48
Opened 2022-06-14 04:33 UTC by toyoshin5

## 目的
学習データの画面を作りたかった
## 更新内容
学習データの画面を作った。
あと任意のカラーコードで色を指定できるColorsクラスのextentionを追加
## 関連するIssue等
特になし
## レビューポイント
特になし
## 留意事項
時間はまだ秒でしか表示できません
## 残課題
なし

2022-06-19 12:41 UTC, noriHanda commented
@toyoshin5 もうレビューしても良い状態？

2022-06-19 13:02 UTC, toyoshin5 commented
お願いします!累計時間がどんな形式で与えられるかわかんなかったのでまた教えて下さい。(日時分秒の文字列そのままなのか秒:Intなのか)

2022-07-16 13:41 UTC, toyoshin5 commented
行数80行まで減らしましたのでよろしくおねがいします!

2022-07-17 02:27 UTC, noriHanda requested changes
ナイス変更！ほぼ問題ないけど、もうちょっとシンプルにできるところと、今後の変更を考えての書き方のところをコメントしました。細かくて申し訳ないけど、また目を通して変更をしてもらえると嬉しいです！

2022-07-17 02:27 UTC, noriHanda commented on lib/screens/learning_data_page/learning_data_page.dart
> +    return MaterialApp(
`MaterialApp` ウィジェットは `main.dart` で宣言してあるから必要ないです！ `Scaffold` から始めてもらうと良いと思う！

2022-07-17 02:27 UTC, noriHanda commented on lib/screens/learning_data_page/learning_data_page.dart
> +        drawer: Drawer(
ここもウィジェットに分けておくと今後変更する人に親切かも！

2022-07-17 02:27 UTC, noriHanda commented on lib/screens/learning_data_page/learning_data_page.dart
> +        appBar: AppBar(
上の `MaterialApp` ウィジェットを外すと、自動的にいい感じに `AppBar` のスタイルが適応されるように設定してあるので、ここに必要なのは `title: Text(hogehoge)` だけで大丈夫です！

2022-07-17 02:27 UTC, noriHanda commented on lib/screens/learning_data_page/learning_data_page.dart
> +                    crossAxisCellCount: (i ~/ 6 + 1) * 3,
何でこの数式にしてあるかコメントで説明してもらえると助かります！

2022-07-17 02:27 UTC, noriHanda commented on pubspec.yaml
> +  flutter_neumorphic: ^3.0.3
これ結局使わなくなったと思うから、消しといてください！

2022-07-24 13:01 UTC, toyoshin5 commented
修正しました!確認お願いします

2022-07-25 01:16 UTC, noriHanda commented
@toyoshin5 確認しました！細かくて本当申し訳ないけど、あと一声修正お願いします 🙇

2022-07-25 01:18 UTC, noriHanda requested changes

2022-07-25 01:18 UTC, noriHanda commented on lib/screens/learning_data_page/learning_data_page.dart
> +        ),
ここに
```dart
leading: const Icon(
          Icons.menu,
          color: Colors.white,
        ),
```
って付け加えないと `AppBar` の色と被っちゃう気がするのでよろしくです！

2025-05-30 12:45 UTC, closed without merging