fix: currentPage>maxPageで結果に遷移
torkralle/notion_wordbook pull request #61
Opened 2022-07-14 04:17 UTC by Reshie

## 目的
currentPageはmaxPageを超えないようにバリデーションする
## 更新内容
- TestResultPage()のルートを定義
- answer_candidate_card.dart内でcurrentPageがmaxPageを超えるときに画面を遷移
## 関連するIssue等
resolves #43
## レビューポイント
- [ ] 実装方法が正しいか
## 留意事項

## 残課題

2022-07-15 13:05 UTC, noriHanda requested changes
@Reshie 忙しい時に実装ありがとう！大方良いと思います！

ただ一点、この変更に加えて、quiz_pageから一覧画面へ戻った場合（interrupt_message.dart から「中断する」を押したとき）に page_controllers.dart の CurrentPageNotifier の state をリセットしないといけないと思いました。あと、ResultPageに遷移させる時にもリセットをする。
この2つのリセットがないと、クイズを始めるときに前回のcurrentPageのstateが持ち越されてしまって、クイズを開こうとしてるのに開けない！ResultPageが出続ける！ってなっちゃうと思います。

2022-07-16 00:51 UTC, noriHanda requested changes
@Reshie 
細かくて申し訳ないけど、 `home_page.dart` でメソッドを何個も呼び出してるところはそれぞれ何のための何のメソッドなのか（メソッドの目的と内容と何でこのタイミングなのか）を書いといてもらえると嬉しいです！よろしくです。

2022-07-19 14:32 UTC, noriHanda commented
@Reshie ごめん、今確認したら8ページ目でなんかエラー出るわ。ちょっと確認&修正お願いして良いでしょうか？
<img src="https://user-images.githubusercontent.com/18581236/179776037-fadf5c4a-0b1e-49cd-8e5e-a4bfb6f8a36d.jpeg" height=500>

```
══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY
╞═══════════════════════════════════════════════════════════
The following RangeError was thrown building DefinitionText(dirty, state:
_ConsumerState#43052):
RangeError (index): Invalid value: Not in inclusive range 0..7: 8

The relevant error-causing widget was:
  DefinitionText
  DefinitionText:file:///Users/norihanda/Projects/notion_wordbook/lib/screens/quiz_page/
  quiz_page.dart:66:24

When the exception was thrown, this was the stack:
#0      List.[] (dart:core-patch/growable_array.dart:264:36)
#1      DefinitionText.build
(package:notion_wordbook/screens/quiz_page/components/definition_text.dart:16:50)
#2      _ConsumerState.build (package:flutter_riverpod/src/consumer.dart:371:19)
#3      StatefulElement.build (package:flutter/src/widgets/framework.dart:4919:27)
#4      ConsumerStatefulElement.build
(package:flutter_riverpod/src/consumer.dart:431:20)
#5      ComponentElement.performRebuild
(package:flutter/src/widgets/framework.dart:4806:15)
#6      StatefulElement.performRebuild
(package:flutter/src/widgets/framework.dart:4977:11)
#7      Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#8      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4787:5)
#9      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4968:11)
#10     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4781:5)
...     Normal element mounting (4 frames)
#14     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3817:16)
#15     MultiChildRenderObjectElement.inflateWidget
(package:flutter/src/widgets/framework.dart:6350:36)
#16     MultiChildRenderObjectElement.mount
(package:flutter/src/widgets/framework.dart:6362:32)
...     Normal element mounting (28 frames)
#44     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3817:16)
#45     MultiChildRenderObjectElement.inflateWidget
(package:flutter/src/widgets/framework.dart:6350:36)
#46     MultiChildRenderObjectElement.mount
(package:flutter/src/widgets/framework.dart:6362:32)
...     Normal element mounting (116 frames)
#162    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3817:16)
#163    MultiChildRenderObjectElement.inflateWidget
(package:flutter/src/widgets/framework.dart:6350:36)
#164    MultiChildRenderObjectElement.mount
(package:flutter/src/widgets/framework.dart:6362:32)
...     Normal element mounting (175 frames)
#339    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3817:16)
#340    MultiChildRenderObjectElement.inflateWidget
(package:flutter/src/widgets/framework.dart:6350:36)
#341    Element.updateChild (package:flutter/src/widgets/framework.dart:3551:18)
#342    RenderObjectElement.updateChildren
(package:flutter/src/widgets/framework.dart:5883:32)
#343    MultiChildRenderObjectElement.update
(package:flutter/src/widgets/framework.dart:6375:17)
#344    Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#345    ComponentElement.performRebuild
(package:flutter/src/widgets/framework.dart:4832:16)
#346    StatefulElement.performRebuild
(package:flutter/src/widgets/framework.dart:4977:11)
#347    Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#348    StatefulElement.update (package:flutter/src/widgets/framework.dart:5009:5)
#349    Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#350    ComponentElement.performRebuild
(package:flutter/src/widgets/framework.dart:4832:16)
#351    Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#352    ProxyElement.update (package:flutter/src/widgets/framework.dart:5154:5)
#353    Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#354    ComponentElement.performRebuild
(package:flutter/src/widgets/framework.dart:4832:16)
#355    Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#356    ProxyElement.update (package:flutter/src/widgets/framework.dart:5154:5)
#357    _InheritedNotifierElement.update
(package:flutter/src/widgets/inherited_notifier.dart:108:11)
#358    Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#359    SingleChildRenderObjectElement.update
(package:flutter/src/widgets/framework.dart:6222:14)
#360    Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#361    ComponentElement.performRebuild
(package:flutter/src/widgets/framework.dart:4832:16)
#362    StatefulElement.performRebuild
(package:flutter/src/widgets/framework.dart:4977:11)
#363    Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#364    StatefulElement.update (package:flutter/src/widgets/framework.dart:5009:5)
#365    Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#366    SingleChildRenderObjectElement.update
(package:flutter/src/widgets/framework.dart:6222:14)
#367    Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#368    SingleChildRenderObjectElement.update
(package:flutter/src/widgets/framework.dart:6222:14)
#369    Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#370    ComponentElement.performRebuild
(package:flutter/src/widgets/framework.dart:4832:16)
#371    Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#372    ProxyElement.update (package:flutter/src/widgets/framework.dart:5154:5)
#373    Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#374    ComponentElement.performRebuild
(package:flutter/src/widgets/framework.dart:4832:16)
#375    StatefulElement.performRebuild
(package:flutter/src/widgets/framework.dart:4977:11)
#376    Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#377    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2659:19)
#378    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:891:21)
#379    RendererBinding._handlePersistentFrameCallback
(package:flutter/src/rendering/binding.dart:370:5)
#380    SchedulerBinding._invokeFrameCallback
(package:flutter/src/scheduler/binding.dart:1146:15)
#381    SchedulerBinding.handleDrawFrame
(package:flutter/src/scheduler/binding.dart:1083:9)
#382    SchedulerBinding._handleDrawFrame
(package:flutter/src/scheduler/binding.dart:997:5)
#386    _invoke (dart:ui/hooks.dart:151:10)
#387    PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:308:5)
#388    _drawFrame (dart:ui/hooks.dart:115:31)
(elided 3 frames from dart:async)

════════════════════════════════════════════════════════════════════════════════════════
════════════

Another exception was thrown: A RenderFlex overflowed by 99529 pixels on the bottom.

Another exception was thrown: RangeError (index): Invalid value: Not in inclusive range
0..7: 8

Another exception was thrown: A RenderFlex overflowed by 99529 pixels on the bottom.

Another exception was thrown: RangeError (index): Invalid value: Not in inclusive range
0..7: 8

Another exception was thrown: A RenderFlex overflowed by 99529 pixels on the bottom.
```

2022-07-21 01:28 UTC, noriHanda commented
@Reshie 原因わかったので修正しときました！

2022-07-21 12:22 UTC, Reshie commented
@noriHanda ありがとうございます🙇‍

2022-07-28 01:33 UTC, merged